[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[dev]
  framework   = "vite"
  command     = "npm run dev"
  port        = 8888     # Combined front-end + functions URL
  targetPort  = 5173     # Vite’s dev server
  functions   = "netlify/functions"
